### ISSUE TITLE
cwd default overridden by executable

### ISSUE THREAD

**Issue by nirvdrum** [graalvm/vscode-extensions#20]
I'm running into an issue with the GraalVM debugger not running in the correct directory. Without having the `cwd` set correctly, none of the project files (e.g., Rakefile or Gemfile) can be found by the executing process.

I haven't debugged the extension yet, so I'm not entirely sure what's going on, but if I do not specify the `cwd` property in my debug configuration, then the working directory is set to the directory that contains the `ruby` process. If I add an entry like `"cwd": "${workspaceFolder}"`, then everything works as I expect. But, that's the documented default value so I assume something in the extension is overriding the value somewhere.

**Comment by entlicher** [comment]
This is fixed by https://github.com/graalvm/vscode-extensions/commit/e1d627805538926b42971efc002809418a6e2964
The `workspaceFolder` is the default now.
A new version of GraalVM extension 0.5.25 was released today, which contains this fix.
