### ISSUE TITLE
The Extension pack is not available. 

### ISSUE THREAD

**Issue by zeronone** [graalvm/vscode-extensions#23]
The extension pack [GraalVM Extension Pack for Java](https://github.com/graalvm/vscode-extensions/tree/master/graalvm-pack#graalvm-extension-pack-for-java), is not available in the marketplace and returns 404.

https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.graalvm-pack

Manually searching also don't yield any results: https://marketplace.visualstudio.com/search?term=graalvm&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by MartinBalin** [comment]
GraalVM Extension Pack was unpublished from Marketplace intentionally. Micronaut extension is still on marketplace renamed to **Micronaut Launch** and **GraalVM Extension** does not longer depend on **Apache NetBeans Language Server**. There was no longer a need to have GraalVM Ext. Pack published.
