### ISSUE TITLE
VisualVM component not available for GraalVM 21

### ISSUE THREAD

**Issue by Marinell0** [graalvm/vscode-extensions#26]
I have been using GraalVM 17 with Java 17 for a long time without any problems. I have been able to use the visualVM integration for a long time. This seems to not work with GraalVM 21:

![image](https://github.com/graalvm/vscode-extensions/assets/34752500/4d28e245-f573-441f-99d6-d51008faa5ed)

Even with the installation active, I do not have the option to even install visualVM as a component.

![image](https://github.com/graalvm/vscode-extensions/assets/34752500/44c409f7-3b40-4a49-b731-49e35d0c9135)

With GraalVM 17 you can see the difference, as it finds the GraalVM Core and Native Image portions of the JDK. (Ignore the Could not resolve components as I'm using a snap version of vscode that doesn't have the GLIBCXX_3.4.29 installed)

In this case, I am able to attach a VisualVM component to the GraalVM instance.

Looks like the GraalVM 21 is not being recognized as a GraalVM JDK

**Comment by MartinBalin** [comment]
This is intentional change in GraalVM 21. GraalVM 17 still contains Graal Updater (GU) lists the components from GDS. GraalVM 21 does not contain GU, does not have components on GDS. The intent of GraalVM team was it is like JDK. So this is as designed.

**Comment by Marinell0** [comment]
So the [documentation](https://www.graalvm.org/latest/tools/vscode/graalvm-extension/visualvm-integration/) for graalvm + visualVM integration for vscode is wrong? There is no way to add visualVM to the vscode using this extension?

**Comment by MartinBalin** [comment]
Seems like documentation there is out dated. Or it has to mention that this feature is available for GraalVM JDK 17 and older.
