### ISSUE TITLE
Cannot debug Micronaut Gradle projects

### ISSUE THREAD

**Issue by raducrisan1** [graalvm/vscode-extensions#3]
I have created a simple gradle micronaut project and I've added a trivial controller:
```java
@Controller("/health")
public class HealthCheck {
    
    @Get()
    public HttpResponse<String> index() {        
        return HttpResponse.ok("success");
    }  
}
```
From VS Code I start debugging the project (F5 shortcut, using default launch.json file). VS Code started the debug mode but if I try to hit this controller from curl I get 
```
{"message":"Page Not Found","_links":{"self":{"href":"/health","templated":false}}}
```
This does not happen if i start the project with `gradle run`. The curl command returns `success`

Is it something that can be addressed into the Micronaut VS Code extension? Or is it something that Micronaut team has to address...

**Comment by MartinBalin** [comment]
This is working now, sorry for late response.
