### ISSUE TITLE
Should restore the services of JDT language server after uninstall NetBeans language server

### ISSUE THREAD

**Issue by testforstephen** [graalvm/vscode-extensions#6]
Currently NetBeans Language Server automatically adds some settings (e.g. `"java.completion.enabled"`, `"java.debug.settings.enableRunDebugCodeLens"`) to my settings.json to disable some clash services of JDT Language Server, but when I uninstall NetBeans Language Server, these settings cannot be restored, which will result in some JDT Language features not being available. This is not a good behavior and I believe most users will not know they need to change the settings manually.

So you'd better change these settings back when users uninstall NetBeans Language Server.

Please refer to the uninstall hook about how to add cleanup steps.
https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook

**Comment by MartinBalin** [comment]
To be fixed in NBLS 12.3.1

**Comment by MartinBalin** [comment]
Looking at the code, we've found it is done per workspace. User experience is that user for project decides which Java provider will be used. Which means uninstall might not be the best possibility. Any advice on what should be used instead?

**Comment by Ondrej-Douda** [comment]
Evaluated work for this feature to be implemented...
There are couple of drawback that makes it difficult, mainly:
- Settings are changed per Workspace
- 'vscode:uninstall' hook is run without VSCode API and after the extension is fully removed from VSCode
- 'deactivate' function is [killed after 5s](https://github.com/Microsoft/vscode/issues/47881#issuecomment-381910587)

Proposal would be to remember all changed Workspaces and theirs respective settings in external file outside the extension to be read by uninstall hook, or to spawn own detached process during deactivation event with similar cleanup but only for single Workspace.
In both versions this feature would need to run external standalone "script" for cleanup without access to VSCode API which is error prone...

**Comment by MartinBalin** [comment]
The whole behaviour changed when GraalVM Ext pack does not set these, but asks for Enabling disabling other Java ext pack per workspace. Closing
