### ISSUE TITLE
Cannot debug Ruby on GraalVM using chromeInspector protocol and default output

### ISSUE THREAD

**Issue by MartinBalin** [graalvm/vscode-extensions#8]
Reported by external user there is an issue with GraalVM extension when generating default launch.json config for debugging Ruby. It does not start.
I had a simple ruby script and had to create following launch.json to make debugger running VSCode GraalVM ext 0.5.6 and GraalVM EE 21.0.0.2 Java 11 and GraalVM CE 21.1.0 JDK11.
```
"configurations": [
        {
            "type": "graalvm",
            "request": "launch",
            "name": "Launch Ruby Script",
            "runtimeExecutable": "ruby",
            "program": "${file}",
            "protocol": "debugAdapter",
            "outputCapture": "std"
        }

    ] 
```
Other combinations don't work.
When having simple hello.rb file with content like
```
 puts 'Hello World'
```
then when launching debugger it also says undefined breakpoint for breakpoint on line 1.

**Comment by dbalek** [comment]
Fixed in 0.5.9.
