### ISSUE TITLE
No "GraalVM" debugger launch environment available

### ISSUE THREAD

**Issue by nirvdrum** [graalvm/vscode-extensions#9]
The [docs for the GraalVM VS Code extension](https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.graalvm) have several sections on debugging various Truffle languages. In each of them, there's some variation of the following:

> To debug a Ruby application running on GraalVM, creating a launch configuration for the application is necessary. To do so, open the application project folder in VS Code (File > Open Folder), then switch to the Debug view by clicking on the "bug" icon in the left-hand side panel. The newly opened window will suggest you create a launch.json file. If debugging is not yet configured (no launch.json has been created), select GraalVM from the list of available debug environmnets [sic].

However, there is no "GraalVM" option available in the list of debug environments. It appears that either the option is missing or the documentation is out of date.

**Comment by MartinBalin** [comment]
There is this list of GraalVM Launch configurations available when you click the Add Configuration in launch.json
![Screenshot 2021-06-17 at 14 59 32](https://user-images.githubusercontent.com/26064232/122401392-d61c3800-cf7c-11eb-80f4-2b348c3e20b2.png)
Is not this what you are looking for and it also starts with **GraalVM** text
